In [75]:
import re
from operator import itemgetter
import numpy as np

data1 = """
6,10
0,14
9,10
0,3
10,4
4,11
6,0
6,12
4,1
0,13
10,12
3,4
3,0
8,4
1,10
2,14
8,10
9,0

fold along y=7
fold along x=5"""

def get_coords(data):
    return [(int(x),int(y)) for x,y in re.findall(r'(\d+),(\d+)', data)]


def get_folds(data):
    return [(axis,int(coord)) for axis,coord in re.findall(r'([xy])=(\d+)', data)]



def get_shape(coords):
    first = itemgetter(0)
    second = itemgetter(1)
    return max(first(xy) for xy in coords)+1, max(second(xy) for xy in coords)+1


def get_array(coords, shape):
    x,y = shape
    array = np.zeros((y,x), dtype=int)
    for x,y in coords:
        array[y,x] = 1
    return array


DEBUG = False

def fold_array(array, axis, coord):
    y,x = array.shape
    if axis == "y":
       top = array[:coord,:] 
       bot = np.flip(array[coord+1:,:], axis=0)
       y = min(top.shape[0], bot.shape[0])
       DEBUG and print(f'{top.shape[0]} == {bot.shape[0]}: {top.shape[0] == bot.shape[0]}')
       return (top | bot)
    if axis == "x":
       lef = array[:,:coord] 
       rig = np.flip(array[:,coord+1:], axis=1)
       x = min(lef.shape[0], rig.shape[0])
       DEBUG and print(f'{lef.shape[0]} == {rig.shape[0]}: {lef.shape[0] == rig.shape[0]}')
       return (lef | rig)
    return np.zeros(shape=(y,x),dtype=int)

       



coords = get_coords(data1)
shape = get_shape(coords)
folds = get_folds(data1)

array = get_array(coords, shape)


print(array)
print(folds)



[[0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0]]
[('y', 7), ('x', 5)]


In [68]:
coords = get_coords(data1)
shape = get_shape(coords)
folds = get_folds(data1)

array = get_array(coords, shape)

for fold in folds:
    array = fold_array(array, *fold)
    break


print(np.count_nonzero(array))



7 == 7: True
17


In [77]:
real_data = open('d13.input').read()
coords = get_coords(real_data)
shape = get_shape(coords)
folds = get_folds(real_data)
array = get_array(coords, shape)

for fold in folds:
    array = fold_array(array, *fold)
    break


print(np.count_nonzero(array))

647


In [83]:
array = get_array(coords, shape)
for fold in folds:
    array = fold_array(array, *fold)

array.shape = array.shape[0], array.shape[1] // 4, 4

for row in array:
    for col in row:
        for c in col:
            print ("#" if c else " ", end="")
    print("")

#  # ####   ## #  #   ## ###   ##    ## 
#  # #       # #  #    # #  # #  #    # 
#### ###     # ####    # #  # #       # 
#  # #       # #  #    # ###  #       # 
#  # #    #  # #  # #  # # #  #  # #  # 
#  # ####  ##  #  #  ##  #  #  ##   ##  
