5


array([0, 0])

In [ ]:
import re
import numpy as np
from math import prod
sample_data = """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""


def get_array(data):
    array = np.array(data, dtype=int)
    array.shape = len(data) // 4, 4
    return array

def get_equals(array):
    for y,row in enumerate(array):
        pass




sample_data = re.findall(r'(\d+)', sample_data)

data = open('d5.input').read()
data = re.findall(r'(\d+)', data)

def condition(array):
    return True


array = get_array(sample_data)
# array = array[np.where((array[:,1] == array[:,3]) | (array[:,0] == array[:,2]))]


width=np.max(array[:,[0,2]]) + 1
height = np.max(array[:,[1,3]]) + 1



grid = np.zeros(width*height, dtype=int)
grid.shape = width,height
grid

def get_sorted(n1, n2):
    start, finish = sorted((n1,n2))
    start, finish = start, finish+1
    return start, finish

for x1,y1,x2,y2 in array:
    if x1 == x2:
        start, finish = get_sorted(y1,y2)
        grid[start:finish, x1] += 1
    if y1 == y2:
        start, finish = get_sorted(x1,x2)
        grid[y1, start:finish] += 1



print (len(np.argwhere(grid>1)))





In [62]:
import re
import numpy as np
from math import prod
sample_data = """0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2"""


def get_array(data):
    array = np.array(data, dtype=int)
    array.shape = len(data) // 4, 4
    return array

def get_equals(array):
    for y,row in enumerate(array):
        pass




sample_data = re.findall(r'(\d+)', sample_data)

data = open('d5.input').read()
data = re.findall(r'(\d+)', data)

def condition(array):
    return True


array = get_array(data)
# array = array[np.where((array[:,1] == array[:,3]) | (array[:,0] == array[:,2]))]


width=np.max(array[:,[0,2]]) + 1
height = np.max(array[:,[1,3]]) + 1



grid = np.zeros(width*height, dtype=int)
grid.shape = width,height

for x1,y1,x2,y2 in array:
    xstep = 1 if x1 < x2 else -1
    ystep = 1 if y1 < y2 else -1
    if x1 == x2:
        grid[y1:y2+ystep:ystep, x1] += 1
    elif y1 == y2:
        grid[y1, x1:x2+xstep:xstep] += 1
    if x1 != x2 and y1 != y2:
        for dy, dx in zip(range(y1,y2+ystep,ystep),range(x1,x2+xstep,xstep)):
            grid[dy,dx] += 1
        


print (grid)
print (len(np.argwhere(grid>1)))





[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
22037
