In [12]:
import re
import numpy as np


sample_data = """2199943210
3987894921
9856789892
8767896789
9899965678"""


width = len(sample_data.split("\n", 1)[0])
data = [int(i) for i in re.findall(r'\d', sample_data)]
array = np.array(data, dtype=int)
array.shape = len(array) //width, width

results = (array.copy() * 0).astype(bool)
results
array_len = len(array)
total = 0
for y,row in enumerate(array):
    for x,col in enumerate(row):
        neighbors = []
        if y > 0:
            neighbors.append(array[y-1,x])
        if y < array_len -1:
            neighbors.append(array[y+1,x])
        if x > 0:
            neighbors.append(array[y,x-1])
        if x < width-1:
            neighbors.append(array[y,x+1])
        if (col < np.array(neighbors)).all():
            results[y,x]=True
            total += col
            total += 1
print(results)
print(total)


[[False  True False False False False False False False  True]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True False False False]]
15


In [19]:
import re
import numpy as np


sample_data = """2199943210
3987894921
9856789892
8767896789
9899965678"""
sample_data = open('d9.input').read()

width = len(sample_data.split("\n", 1)[0])
data = [int(i) for i in re.findall(r'\d', sample_data)]
array = np.array(data, dtype=int)
array.shape = len(array) //width, width

results = (array.copy() * 0).astype(bool)
results
array_len = len(array)
total = 0
for y,row in enumerate(array):
    for x,col in enumerate(row):
        neighbors = []
        if y > 0:
            neighbors.append(array[y-1,x])
        if y < array_len -1:
            neighbors.append(array[y+1,x])
        if x > 0:
            neighbors.append(array[y,x-1])
        if x < width-1:
            neighbors.append(array[y,x+1])
        if (col < np.array(neighbors)).all():
            results[y,x]=True
            total += col
            total += 1
print(results)
print(total)


[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False  True ... False  True False]]
496


In [55]:
import re
import numpy as np


sample_data = """2199943210
3987894921
9856789892
8767896789
9899965678"""

width = len(sample_data.split("\n", 1)[0])

data = [int(i) for i in re.findall(r'\d', sample_data)]

array = np.array(data, dtype=int)

array.shape = len(array) // width, width



array_len = len(array)
total = 0
lows = []


def get_neighbors(array_len,width):
    results = {}
    for y in range(array_len):
        for x in range(width):
            neighbors = []
            if y > 0:
                neighbors.append((y-1,x))
            if y < array_len -1:
                neighbors.append((y+1,x))
            if x > 0:
                neighbors.append((y,x-1))
            if x < width-1:
                neighbors.append((y,x+1))
            results[(y,x)] = tuple(neighbors)
    return results


ntable = get_neighbors(array_len, width)

def get_basin(y,x,basin,array):
    coords = (y,x)
    if coords not in basin:
        basin.append(coords)
    for neighbor in ntable[coords]:
        if neighbor in basin:
            continue
        if array[neighbor] == 9:
            continue
        get_basin(*neighbor,basin,array)
            

visited = []
basin = []
basins = []
print(array)
for y in range(array_len):
    for x in range(width):
        coords = (y,x)
        if array[coords] == 9:
            continue
        if coords in visited:
            continue
        get_basin(y,x,basin,array)
        basins.append(len(basin))
        print(len(basin))
        visited.extend(basin)
        basin = []

import math
print(math.prod(sorted(basins)[-3:]))



[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
3
9
14
9
1134


In [56]:
import re
import numpy as np


sample_data = open('d9.input').read()

width = len(sample_data.split("\n", 1)[0])

data = [int(i) for i in re.findall(r'\d', sample_data)]

array = np.array(data, dtype=int)

array.shape = len(array) // width, width



array_len = len(array)
total = 0
lows = []


def get_neighbors(array_len,width):
    results = {}
    for y in range(array_len):
        for x in range(width):
            neighbors = []
            if y > 0:
                neighbors.append((y-1,x))
            if y < array_len -1:
                neighbors.append((y+1,x))
            if x > 0:
                neighbors.append((y,x-1))
            if x < width-1:
                neighbors.append((y,x+1))
            results[(y,x)] = tuple(neighbors)
    return results


ntable = get_neighbors(array_len, width)

def get_basin(y,x,basin,array):
    coords = (y,x)
    if coords not in basin:
        basin.append(coords)
    for neighbor in ntable[coords]:
        if neighbor in basin:
            continue
        if array[neighbor] == 9:
            continue
        get_basin(*neighbor,basin,array)
            

visited = []
basin = []
basins = []
print(array)
for y in range(array_len):
    for x in range(width):
        coords = (y,x)
        if array[coords] == 9:
            continue
        if coords in visited:
            continue
        get_basin(y,x,basin,array)
        basins.append(len(basin))
        visited.extend(basin)
        basin = []


import math
print(math.prod(sorted(basins)[-3:]))




[[7 9 8 ... 7 5 7]
 [6 7 7 ... 2 4 6]
 [5 4 5 ... 1 3 4]
 ...
 [4 9 8 ... 3 2 9]
 [3 4 9 ... 3 1 2]
 [2 1 0 ... 1 0 1]]
902880
