In [28]:
import numpy as np
import re


sample_data = """11111
19991
19191
19991
11111"""


sample_data = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""


sample_data = open('d11.input').read()

def get_array():
    width = len(sample_data.split("\n", 1)[0])
    data = re.findall(r"\d", sample_data)
    array = np.array(data, dtype=int)
    shape = len(data) // width, width

    array.shape = shape
    return array


In [15]:
def get_neighbors(array_len,width):
    results = {}
    """
    -1,-1  -1,0  -1,+1
         
     0,-1   0,0   0,+1

    +1,-1  +1,0  +1,+1

    """
    for y in range(array_len):
        for x in range(width):
            neighbors = []
            #Top left
            if y > 0 and x > 0:
                neighbors.append((y-1,x-1))

            #Top
            if y > 0:
                neighbors.append((y-1,x))

            #Top right
            if y > 0 and x < width-1:
                neighbors.append((y-1,x+1))

            #Left
            if x > 0:
                neighbors.append((y,x-1))
            
            #Right            
            if x < width-1:
                neighbors.append((y,x+1))
            
            #Bottom left
            if y < array_len -1 and x > 0:
                neighbors.append((y+1,x-1))
                
            #Bottom
            if y < array_len -1:
                neighbors.append((y+1,x))

            #Bottom right
            if y < array_len -1 and x < width-1:
               neighbors.append((y+1,x+1))

            results[(y,x)] = tuple(neighbors)
    return results


In [23]:


neighbors = get_neighbors(*get_array().shape)

def tick_up_neighbors(array,y,x):
    for ny,nx in neighbors[(y,x)]:
        array[ny,nx] += 1
    return array 

def flash_array(array):
    flashes = 0
    results = np.zeros(array.shape, dtype=bool)
    flashed = True
    while flashed:
        flashed = False
        flash_array = np.zeros(array.shape, dtype=bool)
        for y, row in enumerate(array):
            for x, col in enumerate(row):
                if col > 9:
                    if not results[y,x]:
                        flashes += 1
                        results[y,x] = True
                        flash_array[y,x] = True
                        flashed = True
        for y in range(array.shape[0]):
            for x in range(array.shape[1]):
                if flash_array[y,x]:
                    array = tick_up_neighbors(array, y, x)
    array = np.where(results, 0, array)
    return array, flashes

def crunch_steps(array):
    array = array + 1
    flashes = 0
    if (array>9).any():
        array, flashes = flash_array(array)
    return array, flashes
    

In [32]:
array = get_array()
print(array)
flash_total = 0
for _ in range(100):
    array, flashes = crunch_steps(array)
    flash_total += flashes
print("done")
print(array)
print(flash_total)

[[7 1 4 7 7 1 3 5 5 6]
 [6 1 6 7 7 3 3 5 5 5]
 [5 1 8 3 4 8 2 1 1 8]
 [3 8 8 5 4 2 4 5 2 1]
 [7 5 3 3 6 4 4 6 1 1]
 [3 8 7 7 7 6 4 8 6 3]
 [7 6 3 6 8 7 4 3 3 3]
 [8 6 8 7 1 8 8 5 3 3]
 [7 4 6 7 1 1 5 2 6 5]
 [1 6 2 6 5 7 3 1 3 4]]
done
[[9 1 1 1 1 1 1 8 6 5]
 [1 1 1 1 1 1 5 3 8 6]
 [1 1 1 1 1 6 3 2 3 8]
 [1 1 1 1 1 5 2 3 5 1]
 [1 1 1 1 1 9 2 4 1 1]
 [1 1 1 1 1 7 5 7 1 1]
 [1 1 1 1 7 6 3 4 7 1]
 [1 1 1 1 1 7 4 4 7 2]
 [1 1 1 1 1 1 7 7 0 3]
 [6 1 1 1 1 1 2 0 0 3]]
1620


In [33]:
array = get_array()
print(array)
flash_total = 0
steps = 0
while True:
    steps += 1
    array, flashes = crunch_steps(array)
    flash_total += flashes
    if (array == 0).all():
        break
print("done")
print(steps)
print(array)
print(flash_total)

[[7 1 4 7 7 1 3 5 5 6]
 [6 1 6 7 7 3 3 5 5 5]
 [5 1 8 3 4 8 2 1 1 8]
 [3 8 8 5 4 2 4 5 2 1]
 [7 5 3 3 6 4 4 6 1 1]
 [3 8 7 7 7 6 4 8 6 3]
 [7 6 3 6 8 7 4 3 3 3]
 [8 6 8 7 1 8 8 5 3 3]
 [7 4 6 7 1 1 5 2 6 5]
 [1 6 2 6 5 7 3 1 3 4]]
done
371
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
5704
