In [19]:
import re
import numpy as np

In [4]:
sample_data = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7"""

In [23]:
def extract_calls(data):
    return [int(i) for i in data.split("\n", 1)[0].split(",")]



def extract_grids(data):
    grid_raw = re.findall('\d+', data.split("\n", 1)[1])
    array = np.array(grid_raw, dtype=int)
    array.shape = len(grid_raw)//25,5,5
    return array


In [71]:

grids= extract_grids(sample_data)
calls = extract_calls(sample_data)


def crunch_results(grid, result, lastcall):
    return np.sum(grid, where=np.invert(result)) * lastcall

def get_winner(calls, grids):
    calls = calls.copy()
    calls.reverse()
    called = []
    results = (grids.copy() * 0).astype(bool)
    for i in range(50):
        called.append(calls.pop())
        for z,grid in enumerate(grids):
            for y,row in enumerate(grid):
                for x,column in enumerate(row):
                    if column in called:
                        results[z,y,x] = True
                    if results[z,:,x].all():
                        return crunch_results(grids[z,:,:], results[z,:,:], called[-1])
                if results[z,y,:].all():
                    return crunch_results(grids[z,:,:], results[z,:,:], called[-1])
                

get_winner(calls, grids)

4512

In [74]:
data = open('d4.input').read()

grids= extract_grids(data)
calls = extract_calls(data)

get_winner(calls, grids)


5685

In [107]:
def crunch_results(grid, result, lastcall):
    print(grid)
    print(result)
    print(lastcall)
    return np.sum(grid, where=np.invert(result)) * lastcall

def get_last_winner(calls, grids):
    calls = calls.copy()
    calls.reverse()
    results = (grids.copy() * 0).astype(bool)
    windexes = []
    while calls:
        called = calls.pop()
        for z,grid in enumerate(grids):
            if z in windexes:
                continue
            for y,row in enumerate(grid):
                if z in windexes:
                    continue
                for x,column in enumerate(row):
                    if z in windexes:
                        continue
                    if column == called:
                        results[z,y,x] = True
                    if results[z,:,x].all() or results[z,y,:].all():
                        windexes.append(z)
                        break
        if len(windexes) == len(grids):
            last = windexes[-1]
            return crunch_results(grids[last], results[last], called)


grids= extract_grids(sample_data)
calls = extract_calls(sample_data)


get_last_winner(calls, grids)

[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[False False  True  True False]
 [ True False  True  True  True]
 [False False  True False  True]
 [False  True  True  True  True]
 [ True  True  True False False]]
13


1924

In [109]:

data = open('d4.input').read()

grids= extract_grids(data)
calls = extract_calls(data)


get_last_winner(calls, grids)


[[10 43 83 75  8]
 [88 12 38 30  9]
 [60 67 59 76  6]
 [55 45 74 34 25]
 [97 49 65 96 69]]
[[ True  True False  True  True]
 [False  True  True  True  True]
 [ True  True False  True  True]
 [ True  True  True False  True]
 [False  True  True  True False]]
49


21070